### ISSUE TITLE
Unable to find package when enum is present at root of package.

### ISSUE THREAD

**Issue by Disturbing** [njpatel/grpcc#39] opened 2017-09-13 02:55 UTC
I've added an enum at the root of the package of a proto file and the grpc options for packages shows as follows:

https://puu.sh/xyr8B/806119c65a.png

If you wrap the enum in a message, it resolves the problem and shows the proper package for the API.

https://puu.sh/xyr9N/3c5858b4df.png

Please support the following example proto file to ensure that you can find a package even with enum at the root

`
package kintohub.authblock.generated;

service AuthBlock {
	rpc Login(LoginRequest) returns (LoginResponse) {
		option (google.api.http) = {
			post: "/auth/login"
			body: "*"
		};
	}

	rpc Register(CreateRequest) returns (CreateResponse) {
		option (google.api.http) = {
			post: "/auth/register"
			body: "*"
		};
	}

	rpc ValidateEmail(ValidateEmailRequest) returns (ValidateEmailResponse) {
		option (google.api.http).get = "/auth/validate";
	}

	//	rpc ForgotPassword(ForgotPasswordRequest) returns (ForgotPasswordResponse) {
	//		option (google.api.http) = {
	//			post: "/auth/forgotpassword"
	//			body: "*"
	//		};
	//	}
	//
	//	rpc ResetPassword(ResetPasswordRequest) returns (ResetPasswordResponse) {
	//		option (google.api.http) = {
	//			post: "/auth/resetpassword"
	//			body: "*"
	//		};
	//	}
}

message SessionData {
	enum SessionRole {
		GUEST = 0;
		AUTHED_USER = 1;
	};
}

`

Environment: Windows 10 64bit, grpcc version 0.0.8, Protobuf 3.4.0, GRPC 1.4.0

**Comment by yukw777** [comment] 2017-09-26 22:00
Instead of parsing through the proto file, wouldn't it be easier to add an option to pass in the package name?

**Comment by Disturbing** [comment] 2017-09-26 23:55
Can you provide example?

Also the service name does not show up as an option when you have enum as
base so, it may be bugging out.

**Comment by yukw777** [comment] 2017-09-27 18:38
Something like...
```
$ grpcc --proto ./service/myservice.proto --address 127.0.0.1:3466 --package package.name
```

And yeah, this function is not behaving correctly: https://github.com/njpatel/grpcc/blob/master/lib/index.js#L41

I feel like that approach is quite hacky and convoluted. I'd say we should forget about trying to figure out all the services automatically (unless `grpc` library has a way to do this nicely) and just let the user enter the package name.

**Comment by Disturbing** [comment] 2017-10-04 00:00
Agreed

**Comment by netdragonboberb** [comment] 2017-10-09 03:42
Dupe of #31

**Comment by njpatel** [comment] 2017-10-20 10:52
Closing as dupe of #31, should have a release today that fixes this.

**Closed by njpatel** 2017-10-20 10:52 UTC
